---
title: "Análisis Exploratorio de Datos"
author: "Alberto Barradas"
format: 
    revealjs:
        slideNumber: true
        center: true
        controls: true
        progress: true
        history: true
        # transition: 'slide'
        # theme: 'black'
        theme: 'white'
        width: 1920
        height: 1080
        margin: 0.1
        # hash: true
        # separator: '^\n---\n'
        # verticalSeparator: '^\n--\n'
    beamer: 
        aspectratio: 169
        theme: "default"
        colorlinks: true
    pdf:
        number-sections: true
        colorlinks: true
    html:
        code-fold: true
code-fold: true
jupyter: julia-1.11
bibliography: references.bib
---

## Temario

:::: {.columns}

::: {.column width=50%}
- Muestreo y Distribución Probabilística
- Estadísticas Descriptivas
- Histogramas y Densidades
:::

::: {.column width=50%}
- Distribución Normal
- Distribución t de Student
- Esquema de Tests de Hipótesis
- Pruebas Paramétricas y No Paramétricas
:::

::::

## Recordatorio
:::: {.columns}

::: {.column width=50%}

En Probabilidad y Estadística, una variable aleatoria es **una función que asigna un valor numérico al resultado de un experimento aleatorio**.

La variable no tiene un solo valor numérico, sino que puede tomar varios valores numéricos, cada uno con una cierta probabilidad.

Una forma de describir esa probabilidad es mediante una función de probabilidad, que asigna a cada valor numérico posible de la variable aleatoria una probabilidad.

:::

::: {.column width=50%}

```{julia}
#| echo: true
#| output: slide
#| label: static-sample
#| fig-cap: "Muestreo de una población"
using GLMakie
using Distributions, Random, HypothesisTests

U = 1000
N = 10
X = rand(U)
t = sample(1:length(X), N)
x = X[t]
fig = Figure(size=(800, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:teal)
scatter!(ax, t, x, color=:coral, marker=:xcross, markersize=20)
fig
```

:::

::::


## Muestreo

```{julia}
#| echo: true
#| output: slide
#| label: sample
#| fig-cap: "Muestreo de una población"
# Muestreo de una población
U = 10000
N = 10
X = Observable(rand(U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:teal)
scatter!(ax, t, x, color=:coral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:teal)
hist!(ax, x, color=:coral,  normalization=:pdf, bins=100)
button = Button(fig[2, :], label="Tomar Nueva Muestra")
l = on(button.clicks) do b
    t[] = sample(1:length(X[]), N)
    x[] = X[][t[]]
end
# sg = SliderGrid(fig[2,1],
#     (label="N", range=1:1:N, startvalue=N),
# )
# sliderobservables = [s.value for s in sg.sliders]
# bars = lift(sliderobservables...) do N
#     t[] = sample(1:length(X[]), N)
#     x[] = X[][t[]]
# end
fig
```

## Distribución de Probabilidad

Hemos utilizado distribuciones uniformes, como las de aventar un dado. Estas variables aleatorias pueden tomar cualquiera de sus valores con la misma probabilidad, pero esto no tiene que ser así. Si un dado está cargado, la probabilidad de que salgan ciertos numeros es mayor que otros.

Una distribución de probabilidad describe cómo se distribuyen los valores de una variable aleatoria y la probabilidad de que la variable aleatoria tome un valor específico.

Recomendamos que memoricen dos distribuciones de probabilidad con sus parámetros:

```{julia}
#| echo: true
#| output: slide
#| label: distributions
#| fig-cap: "Distribuciones de Probabilidad"
U = 1000
N = 30
X = Observable(rand(Normal(0, 1), U))
# X = Observable(rand(Uniform(0, 1), U))
# X = Observable(rand(Exponential(1), U))
# X = Observable(rand(Binomial(10, 0.5), U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:teal)
scatter!(ax, t, x, color=:coral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:teal)
hist!(ax, x, color=:coral,  normalization=:pdf)
button = Button(fig[2, 1:2], label="Tomar Nueva Muestra")
l = on(button.clicks) do b
    x[] = sample(X[], N)
    println("Estadísticas Descriptivas de la Muestra:")
    println("Media: ", mean(x[]))
    println("Mediana: ", median(x[]))
    println("Desviación Estándar: ", std(x[]))
end
fig
```

## Distribución normal

No todas las distribuciones aleatorias tienen la misma probabilidad de ocurrencia. La distribución normal es una de las distribuciones más comunes en estadística: es simétrica y tiene una forma de campana. También es una distribución continua, lo que significa que puede tomar cualquier valor en un rango continuo.

$$
f(x | \mu, \sigma^2) = \frac{1}{\sqrt{2 \pi \sigma^2}} e^{-\frac{(x - \mu)^2}{2\sigma^2}}
$$

```{julia}
#| echo: true
#| output: slide
#| label: normal
#| fig-cap: "Distribucion Normal"
U = 10000
N = 10
X = Observable(rand(Normal(0, 1), U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:mediumaquamarine)
scatter!(ax, t, x, color=:lightcoral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:mediumaquamarine)
hist!(ax, x, color=:lightcoral,  normalization=:pdf)
button = Button(fig[2, 1:2], label="Tomar Nueva Muestra")
l = on(button.clicks) do b
    x[] = sample(X[], N)
end
fig
```

---

La distribución normal puede ser descrita por dos parametros: `μ` y `σ`, que representan la media y la desviación estándar de la distribución. Cambiando los valores de `μ` y `σ`, podemos cambiar la forma de la distribución:

```{julia}
#| echo: true
#| output: slide
#| label: normal-params
#| fig-cap: "Parámetros de la Distribución Normal"
U = 10000
N = 10
μ = Observable(0.0)
σ = Observable(1.0)
X = Observable(rand(Normal(μ[], σ[]), U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:mediumaquamarine)
scatter!(ax, t, x, color=:lightcoral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:mediumaquamarine)
hist!(ax, x, color=:lightcoral,  normalization=:pdf)
sg = SliderGrid(fig[2,1],
    (label="μ", range=-10:0.1:10, format="{:.2f}", startvalue=0.0),
    (label="σ", range=0.1:0.1:5, format="{:.2f}", startvalue=1.0),
)
sliderobservables = [s.value for s in sg.sliders]
bars = lift(sliderobservables...) do μ, σ
    X[] = rand(Normal(μ, σ), U)
    t[] = sample(1:length(X[]), N)
    x[] = X[][t[]]
    println("Estadísticas Descriptivas de la Muestra:")
    println("Media: ", mean(x[]))
    println("Mediana: ", median(x[]))
    println("Desviación Estándar: ", std(x[]))
end
fig
```

---

Generando una distribución sintética para tres valores de `μ`:
```{julia}
#| echo: false
#| output: slide
#| label: normal-params-mu
#| fig-cap: "Parámetros de la Distribución Normal"
Random.seed!(42) # para reproducibilidad
U = 10000
N = 100
σ = 2.0
μs = [-1.0, 0.0, 1.0]
Xs = [rand(Normal(μ, σ), U) for μ in μs]
ts = [sample(1:length(X), N) for X in Xs]
xs = [X[t] for (X, t) in zip(Xs, ts)]
fig = Figure(size=(1600, 600));
for i in 1:3
    ax = Axis(fig[1, i], subtitle="μ=$(μs[i])")
    scatter!(ax, Xs[i], color=:mediumaquamarine)
    scatter!(ax, ts[i], xs[i], color=:lightcoral, marker=:xcross, markersize=20)
    ax = Axis(fig[2, i], subtitle="Distribución")
    density!(ax, Xs[i], color=:mediumaquamarine)
    hist!(ax, xs[i], color=:lightcoral,  normalization=:pdf)
end
# save samples as csv with headers mu, sample
using CSV, DataFrames
df = DataFrame(mu=Float64[], sample=Float64[])
for i in 1:3
    for val in xs[i]
        push!(df, (μs[i], val))
    end
end
CSV.write("normal_samples.csv", df)
fig
```


```{julia}
#| echo: false
#| output: slide
#| label: normal-params-sigma
#| fig-cap: "Parámetros de la Distribución Normal"
Random.seed!(42) # para reproducibilidad
N = 30
μ1 = 0.0
σ1 = 1.0
μ2 = 0.1
σ2 = 1.0
X1 = rand(Normal(μ1, σ1), N)
X2 = rand(Normal(μ2, σ2), N)
df = DataFrame(mu=Float64[], sigma=Float64[], sample=Float64[])
for val in X1
    push!(df, (μ1, σ1, val))
end
for val in X2
    push!(df, (μ2, σ2, val))
end
CSV.write("normal_samples_small_effect.csv", df)
```

```{julia}
#| echo: true
#| output: slide
#| label: normal-params-sigma-plot
#| fig-cap: "Parámetros de la Distribución Normal"
Random.seed!(42) # para reproducibilidad
N = 30
μ1 = 0.0
σ1 = 1.0
μ2 = 0.5
σ2 = 1.0
X1 = rand(Normal(μ1, σ1), N)
X2 = rand(Normal(μ2, σ2), N)
df = DataFrame(mu=Float64[], sigma=Float64[], sample=Float64[])
for val in X1
    push!(df, (μ1, σ1, val))
end
for val in X2
    push!(df, (μ2, σ2, val))
end
CSV.write("normal_samples_medium_effect.csv", df)
```


## Distribución t de Student
La distribución t de Student es una distribución de probabilidad continua que se utiliza para estimar la media de una población cuando el tamaño de la muestra es pequeño y/o la desviación estándar de la población es desconocida. La distribución t de Student es similar a la distribución normal, pero tiene colas más gruesas, lo que significa que hay una mayor probabilidad de obtener valores extremos.

$$
f(t | \nu) = \frac{\Gamma\left(\frac{\nu + 1}{2}\right)}{\sqrt{\nu \pi} \Gamma\left(\frac{\nu}{2}\right)} \left(1 + \frac{t^2}{\nu}\right)^{-\frac{\nu + 1}{2}}
$$

```{julia}
#| echo: true
#| output: slide
#| label: tstudent
#| fig-cap: "Distribución t de Student"
U = 1000
N = 30
df = Observable(29) # grados de libertad
X = Observable(rand(TDist(df[]), U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:mediumaquamarine)
scatter!(ax, t, x, color=:lightcoral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:mediumaquamarine)
hist!(ax, x, color=:lightcoral,  normalization=:pdf)
button = Button(fig[2, 1:2], label="Tomar Nueva Muestra")
l = on(button.clicks) do b
    x[] = sample(X[], N)
    println("Estadísticas Descriptivas de la Muestra:")
    println("Media: ", mean(x[]))
    println("Mediana: ", median(x[]))
    println("Desviación Estándar: ", std(x[]))
end
fig
```

Comparada con la distribución normal, la distribución t de Student tiene colas más gruesas, lo que significa que hay una mayor probabilidad de obtener valores extremos. A medida que el tamaño de la muestra aumenta, la distribución t de Student se aproxima a la distribución normal.

```{julia}
#| echo: true
#| output: slide
#| label: compare
#| fig-cap: "Comparación entre la Distribución Normal y la Distribución t de Student"
U = 10000
N = Observable(5)
df = N[] - 1 # grados de libertad
X1 = Observable(rand(Normal(0, 1), U))
X2 = Observable(rand(TDist(df), U))
t = Observable(sample(1:length(X1[]), N[]))
x1 = Observable(X1[][t[]])
x2 = Observable(X2[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X1, color=:teal, label="Normal")
scatter!(ax, t, x1, color=:coral, marker=:xcross, markersize=20)
scatter!(ax, X2, color=:mediumaquamarine, label="t Student")
scatter!(ax, t, x2, color=:lightcoral, marker=:xcross, markersize=20)
axislegend(ax)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X1, color=:teal, label="Normal")
hist!(ax, x1, color=:coral,  normalization=:pdf, label="Normal")
density!(ax, X2, color=:mediumaquamarine, label="t Student")
hist!(ax, x2, color=:red,  normalization=:pdf, label="t Student")
axislegend(ax)
button = Button(fig[2, 1:2], label="Tomar Nueva Muestra")
l = on(button.clicks) do b
    t[] = sample(1:length(X1[]), N[])
    x1[] = X1[][t[]]
    x2[] = X2[][t[]]
    df = N[] - 1
end
fig
```

## Distribución Log-Normal
La distribución log-normal es una distribución de probabilidad continua que se utiliza para modelar variables aleatorias que son el resultado de la multiplicación de varias variables aleatorias independientes. La distribución log-normal tiene dos parámetros: la media `μ` y la desviación estándar `σ` de la variable logarítmica.
$$
f(x | \mu, \sigma) = \frac{1}{x \sigma \sqrt{2 \pi}} e^{-\frac{(\ln(x) - \mu)^2}{2\sigma^2}}
$$

```{julia}
#| echo: true
#| output: slide
#| label: lognorm
#| fig-cap: "Distribución de Log-Normal"
U = 10000
N = 10
μ = Observable(0.0)
σ = Observable(1.0)
X = Observable(rand(LogNormal(μ[], σ[]), U))
t = Observable(sample(1:length(X[]), N))
x = Observable(X[][t[]])
fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1], subtitle="Muestra de Población")
scatter!(ax, X, color=:mediumaquamarine)
scatter!(ax, t, x, color=:lightcoral, marker=:xcross, markersize=20)
ax = Axis(fig[1, 2], subtitle="Distribución")
density!(ax, X, color=:mediumaquamarine)
hist!(ax, x, color=:lightcoral,  normalization=:pdf)
sg = SliderGrid(fig[2,1],
    (label="μ", range=0:0.01:3, format="{:.2f}", startvalue=0.0),
    (label="σ", range=0.1:0.01:1, format="{:.2f}", startvalue=1.0),
)
sliderobservables = [s.value for s in sg.sliders]
bars = lift(sliderobservables...) do μ, σ
    X[] = rand(LogNormal(μ, σ), U)
    t[] = sample(1:length(X[]), N)
    x[] = X[][t[]]
    println("Estadísticas Descriptivas de la Muestra:")
    println("Media: ", mean(x[]))
    println("Mediana: ", median(x[]))
    println("Desviación Estándar: ", std(x[]))
end
fig
```

Distribución sintética para tres valores de `μ`:
```{julia}
#| echo: false
#| output: slide
#| label: lognorm-params-mu
#| fig-cap: "Parámetros de la Distribución Log-Normal"
Random.seed!(42) # para reproducibilidad
U = 10000
N = 100
σ = 0.5
μs = [0.3, 0.7, 1.0]
Xs = [rand(LogNormal(μ, σ), U) for μ in μs]
ts = [sample(1:length(X), N) for X in Xs]
xs = [X[t] for (X, t) in zip(Xs, ts)]
fig = Figure(size=(1600, 600));
for i in 1:3
    ax = Axis(fig[1, i], subtitle="μ=$(μs[i])")
    scatter!(ax, Xs[i], color=:mediumaquamarine)
    scatter!(ax, ts[i], xs[i], color=:lightcoral, marker=:xcross, markersize=20)
    ax = Axis(fig[2, i], subtitle="Distribución")
    density!(ax, Xs[i], color=:mediumaquamarine)
    hist!(ax, xs[i], color=:lightcoral,  normalization=:pdf)
end
# save samples as csv with headers mu, sample
using CSV, DataFrames
df = DataFrame(mu=Float64[], sample=Float64[])
for i in 1:3
    for val in xs[i]
        push!(df, (μs[i], val))
    end
end
CSV.write("lognormal_samples.csv", df)
fig
```

## Pruebas de Hipótesis
Una prueba de hipótesis es un procedimiento estadístico que se utiliza para tomar una decisión sobre una afirmación acerca de un parámetro de una población. La afirmación que se está probando se llama hipótesis nula (H0) y la afirmación alternativa se llama hipótesis alternativa (H1). La prueba de hipótesis se basa en la probabilidad de obtener un resultado tan extremo como el observado, si la hipótesis nula es verdadera. Si la probabilidad es baja, se rechaza la hipótesis nula.

```{julia}
#| echo: true
#| output: slide
#| label: hypothesis
#| fig-cap: "Pruebas de Hipótesis"
U = 100000
N = 1000
μ1 = Observable(0.0)
σ1 = Observable(1.0)

μ2 = Observable(0.0)
σ2 = Observable(1.0)

μ3 = sum([μ1[], μ2[]])
σ3 = sqrt(σ1[]^2 + σ2[]^2)

x = range(-10, 10, length=U)
y1 = Observable(pdf(Normal(μ1[], σ1[]), x))
y2 = Observable(pdf(Normal(μ2[], σ2[]), x))
# y3 = Observable(pdf(Normal(μ3[], σ3[]), x))
α = Observable([quantile(Normal(μ1[], σ1[]), 0.95)])
β = Observable([quantile(Normal(μ2[], σ2[]), 0.20)])
p = Observable(pvalue(SignedRankTest(y1[], y2[])))

fig = Figure(size=(1600, 600));
ax = Axis(fig[1, 1])
l1 = lines!(ax, x, y1, color=:teal, linewidth=10)
l2 = lines!(ax, x, y2, color=:coral, linewidth=10)
# l3 = lines!(ax, x, y3, color=:orchid, linewidth=10)
lα = vlines!(ax, α, color=:black, linestyle=:dash, linewidth=1)
lβ = vlines!(ax, β, color=:red, linestyle=:dash, linewidth=1)
Legend(fig[1, 2], [l1, l2, lα, lβ], ["H0", "H1", "p=0.05", "Power=.80"])
lab = Label(fig[2, 2], "p=$(round(p[], digits=4))")
fig

# SliderGrid
sg = SliderGrid(fig[2,1],
    (label="μ1", range=-5:0.1:5, format="{:.2f}", startvalue=0.0),
    (label="σ1", range=0.1:0.1:5, format="{:.2f}", startvalue=1.0),
    (label="μ2", range=-5:0.1:5, format="{:.2f}", startvalue=0.0),
    (label="σ2", range=0.1:0.1:5, format="{:.2f}", startvalue=1.0),
    (label="N", range=10:10:U, format="{:.0f}", startvalue=N),
)
sliderobservables = [s.value for s in sg.sliders]
bars = lift(sliderobservables...) do μ1, σ1, μ2, σ2, N
    # μ3 = μ1 + μ2
    # σ3 = sqrt(σ1^2 + σ2^2)
    y1[] = pdf(Normal(μ1, σ1), x)
    y2[] = pdf(Normal(μ2, σ2), x)
    # y3[] = pdf(Normal(μ3, σ3), x)
    α[] = [quantile(Normal(μ1, σ1), 0.95)]
    β[] = [quantile(Normal(μ2, σ2), 0.20)]
    p[] = pvalue(SignedRankTest(sample(y1[], N), sample(y2[], N)))
    lab.text[] = "p*=$(round(p[], digits=4))"
end

fig
```

## Referencias
::: {#refs}
:::